name: soyabox_pos
description: A Flutter Point of Sale application for restaurants with multi-language support.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  get_storage: ^2.1.1
  permission_handler: ^11.0.1
  esc_pos_printer: ^6.0.0
  bluetooth_thermal_printer: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/localization/assets/

flutter_intl:
  enabled: true